version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "0.0.0.0:3000:2000"
    env_file:
      - .env
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - my_network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my_network

networks:
  my_network:
